/gps/verbose 2
/gps/particle gamma
/gps/pos/type Point
/gps/pos/centre 0. 0. -12.5 cm

# Angular distribution
/gps/ang/type iso

# Position distribution
#/gps/pos/shape Circle
#/gps/pos/radius 5 mm

# Energy distribution
/gps/ene/type User
/gps/hist/type energy
/gps/hist/point 0.34714 0.0075
/gps/hist/point 0.8261 0.0076
/gps/hist/point 1.173228 99.85
/gps/hist/point 1.332492 99.9826
/gps/hist/point 2.15857 0.0012
/gps/hist/point 2.505692 0.000002

